# Generated by Django 5.1.1 on 2024-10-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciohistoricovehiculos',
            name='color',
            field=models.CharField(default='Desconocido'),
        ),
        migrations.AlterField(
            model_name='preciohistoricovehiculos',
            name='modelo',
            field=models.TextField(max_length=120),
        ),
    ]
