# Generated by Django 5.1.1 on 2024-10-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migraciones', '0002_color'),
    ]

    operations = [
    ]
